### ISSUE TITLE
numpad

### ISSUE THREAD

**Issue by Kraun89** [3noix/MyMFD#1]
Hi! Is there any way to use also the numpad keys?

**Comment by 3noix** [comment]
Hi! I added and tested other keys (CapsLock, most of the numpad, and F keys after F12). I also added 11 other keys that does not work as expected for me or my setup (french keyboard with french language in Windows): from line 114 to 124 in KeyStrokeGenerator.cpp.

**Comment by 3noix** [comment]
For info and for traceability, I use:
- [SendInput](https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-sendinput) function
- I define the [KEYBDINPUT](https://docs.microsoft.com/en-us/windows/win32/api/winuser/ns-winuser-keybdinput) using the "scan code mode": I give the [virtual key codes](https://docs.microsoft.com/en-us/windows/win32/inputdev/virtual-key-codes) and transform them into scan codes using "MapVirtualKey"

I did many tests several years ago and this was the solution I retained at that time... but I forgot why exactly and it would deserve another attempt.

**Comment by 3noix** [comment]
I added a binary release 1.2.0 with these additions and a few other commits.

**Comment by Kraun89** [comment]
wonderfull, thanks  a lot! ;-)
